### ISSUE TITLE
[Google Drive] AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by llermaly** [elastic/connectors-python#1408]
## Bug Description
When running a ACL's ingestion I see the following error and no users are fetched:

`AttributeError: 'NoneType' object has no attribute 'get'`

Full logs:

```
[FMWK][18:18:09][INFO] [Sync Job id: Xn6F24kBHCd82NGeDR0K, connector id: _U9924kBXR2X9WEnzYkV, index name: .search-acl-filter-***-gdrive] Starting access control doc lookups
[FMWK][18:18:09][DEBUG] [Sync Job id: Xn6F24kBHCd82NGeDR0K, connector id: _U9924kBXR2X9WEnzYkV, index name: .search-acl-filter-**-gdrive] Scanning existing index .search-acl-filter-**-gdrive
[FMWK][18:18:09][DEBUG] [Sync Job id: Xn6F24kBHCd82NGeDR0K, connector id: _U9924kBXR2X9WEnzYkV, index name: .search-acl-filter-**-gdrive] Size of 0 access control document ids  in memory is 0.0MiB
Task exception was never retrieved
future: <Task finished name='Task-90' coro=<Sink.run() done, defined at /app/connectors/es/sink.py:171> exception=Exception('mapper [size] cannot be changed from type [long] to [text]')>
Traceback (most recent call last):
  File "/app/connectors/es/sink.py", line 173, in run
    await self._run()
  File "/app/connectors/es/sink.py", line 234, in _run
    await self._batch_bulk(batch, stats)
  File "/app/connectors/logger.py", line 196, in _awrapped
    return await func(*args, **kw)
  File "/app/connectors/es/sink.py", line 145, in _batch_bulk
    raise Exception(data["error"]["reason"])
Exception: mapper [size] cannot be changed from type [long] to [text]
[FMWK][18:18:14][DEBUG] [get_doc call] 0-_decorate_with_metrics_span took 4.811801195144653 seconds.
[FMWK][18:18:14][CRITICAL] [Sync Job id: Xn6F24kBHCd82NGeDR0K, connector id: _U9924kBXR2X9WEnzYkV, index name: .search-acl-filter-**-gdrive] The document fetcher failed
Traceback (most recent call last):
  File "/app/connectors/es/sink.py", line 547, in get_access_control_docs
    async for doc in generator:
  File "/app/connectors/logger.py", line 176, in __anext__
    return await self.gen.__anext__()
  File "/app/connectors/es/sink.py", line 360, in _decorate_with_metrics_span
    async for doc in generator:
  File "/app/connectors/sync_job_runner.py", line 353, in generator
    async for doc in self.data_provider.get_access_control():
  File "/app/connectors/sources/google_drive.py", line 735, in get_access_control
    async for access_control_doc in self.prepare_access_control_documents(
  File "/app/connectors/sources/google_drive.py", line 716, in prepare_access_control_documents
    prepared_ac_docs = await self._process_items_concurrently(
  File "/app/connectors/sources/google_drive.py", line 671, in _process_items_concurrently
    return await asyncio.gather(*tasks)
  File "/app/connectors/sources/google_drive.py", line 662, in process_item
    return await process_item_func(item)
  File "/app/connectors/sources/google_drive.py", line 690, in prepare_single_access_control_document
    for group in groups_page.get("groups", []):
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by llermaly** [comment]
@jedrazb Confirmed. it throws error because a user has no groups. 

I added this: `if groups_page:` in line 697 and its fixed, but I have no idea if this will work for all the code. At least I see the users now.

**Comment by jedrazb** [comment]
> it throws error because a user has no groups.
Thank you for reporting the reason for the error, it will help me with reproducing this behaviour locally :) on it, will have a fix soon.
