### ISSUE TITLE
[SPO] Empty error message: "Sync failure: . "

### ISSUE THREAD

**Issue by llermaly** [elastic/connectors-python#1603]
## Bug Description
Sometimes the Sync failure error in Kibana comes empty:

## Expected behavior
We should capture and display empty errors properly

## Screenshots
![image](https://github.com/elastic/connectors-python/assets/8575569/046d5435-3059-44fe-a2b8-a504bf476ba8)

## Environment
Cloud

## Additional context
Not sure how to reproduce this, If I can reproduce it I will attach details.

**Comment by artem-shelkovnikov** [comment]
Unfortunately without details to reproduce it's not possible to address this - connector returned an error that had a message which is an empty string. We need to find what part of connector returned it.

**Comment by llermaly** [comment]
I could reproduce. It shows empty error when throws 429.

```
[FMWK][18:18:08][CRITICAL] [Sync Job id: zjoQkIoB26kkwmCbmNnM, connector id: zToNkIoB26kkwmCbxNkF, index name: search-xxx-pick27] The document fetcher failed
Traceback (most recent call last):
  File "/Users/gustavollermalylarrain/Documents/proyectos/elastic/xxxx/connectors-python/connectors/sources/sharepoint_online.py", line 402, in _get
    async with self._http_session.get(
  File "/Users/gustavollermalylarrain/Documents/proyectos/elastic/xxx/connectors-python/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/Users/gustavollermalylarrain/Documents/proyectos/elastic/xxx/connectors-python/lib/python3.10/site-packages/aiohttp/client.py", line 643, in _request
    resp.raise_for_status()
  File "/Users/gustavollermalylarrain/Documents/proyectos/elastic/xxx/connectors-python/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 429, message='', url=URL('https://xxx.sharepoint.com/sites/retail/_api/lists/GetByTitle('Field%20Leadership%20%20Licensed%20Stores')/items(7384)/HasUniqueRoleAssignments')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/gustavollermalylarrain/Documents/proyectos/elastic/xxx/connectors-python/connectors/es/sink.py", line 387, in get_docs
    async for count, doc in aenumerate(generator):
  File "/Users/gustavollermalylarrain/Documents/proyectos/elastic/xxx/connectors-python/connectors/utils.py", line 689, in aenumerate
    async for elem in asequence:
  File "/Users/gustavollermalylarrain/Documents/proyectos/elastic/xxx/connectors-python/connectors/logger.py", line 134, in __anext__
    return await self.gen.__anext__()
  File "/Users/gustavollermalylarrain/Documents/proyectos/elastic/xxx/connectors-python/connectors/es/sink.py", line 360, in _decorate_with_metrics_span
    async for doc in generator:
  File "/Users/gustavollermalylarrain/Documents/proyectos/elastic/xxx/connectors-python/connectors/sync_job_runner.py", line 310, in prepare_docs
    async for doc, lazy_download, operation in self.generator():
  File "/Users/gustavollermalylarrain/Documents/proyectos/elastic/xxx/connectors-python/connectors/sync_job_runner.py", line 342, in generator
    async for doc, lazy_download in self.data_provider.get_docs(
  File "/Users/gustavollermalylarrain/Documents/proyectos/elastic/xxx/connectors-python/connectors/sources/sharepoint_online.py", line 1547, in get_docs
    async for list_item, download_func in self.site_list_items(
  File "/Users/gustavollermalylarrain/Documents/proyectos/elastic/xxx/connectors-python/connectors/sources/sharepoint_online.py", line 1802, in site_list_items
    await self.client.site_list_item_has_unique_role_assignments(
  File "/Users/gustavollermalylarrain/Documents/proyectos/elastic/xxx/connectors-python/connectors/sources/sharepoint_online.py", line 715, in site_list_item_has_unique_role_assignments
    response = await self._rest_api_client.fetch(url)
  File "/Users/gustavollermalylarrain/Documents/proyectos/elastic/xxx/connectors-python/connectors/sources/sharepoint_online.py", line 331, in fetch
    return await self._get_json(url)
  File "/Users/gustavollermalylarrain/Documents/proyectos/elastic/xxx/connectors-python/connectors/sources/sharepoint_online.py", line 371, in _get_json
    async with self._get(absolute_url) as resp:
  File "/Users/gustavollermalylarrain/miniforge3/envs/connector/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/Users/gustavollermalylarrain/Documents/proyectos/elastic/xxx/connectors-python/connectors/sources/sharepoint_online.py", line 295, in wrapped
    async for item in func(*args, **kwargs):
  File "/Users/gustavollermalylarrain/Documents/proyectos/elastic/xxx/connectors-python/connectors/sources/sharepoint_online.py", line 413, in _get
    await self._handle_client_response_error(absolute_url, e)
  File "/Users/gustavollermalylarrain/Documents/proyectos/elastic/xxx/connectors-python/connectors/sources/sharepoint_online.py", line 430, in _handle_client_response_error
    raise ThrottledError from e
connectors.sources.sharepoint_online.ThrottledError
[FMWK][18:18:11][INFO] [Sync Job id: zjoQkIoB26kkwmCbmNnM, connector id: zToNkIoB26kkwmCbxNkF, index name: search-xxx-pick27] Job reporting task is stopped.
[FMWK][18:18:12][INFO] [Sync Job id: zjoQkIoB26kkwmCbmNnM, connector id: zToNkIoB26kkwmCbxNkF, index name: search-xxx-pick27] Sync done: 38897 indexed, 0 deleted. (12955 seconds)
```

![CleanShot 2023-09-13 at 18 23 10](https://github.com/elastic/connectors-python/assets/8575569/947fb11c-ba51-4dd1-a534-b209ffdcc7e8)
