### ISSUE TITLE
`test_ping_for_failed_connection` blocks on macOS

### ISSUE THREAD

**Issue by tarekziade** [elastic/connectors-python#315]
### Problem Description

running `make test` - connectors/sources/tests/test_abs.py::test_ping_for_failed_connection blocks

**Comment by tarekziade** [comment]
well actually it works! but it takes 88 seconds for that single test. 

```
[FMWK][09:45:16][ERROR] Error while connecting to the Azure Blob Storage.
Traceback (most recent call last):
  File "/Users/tarekziade/Dev/connectors-python/lib/python3.10/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 61] Connect call failed ('127.0.0.1', 10000)
```


I suspect we miss a timeout somewhere cc @praveen-elastic

**Comment by parth-crest** [comment]
@tarekziade Sure, we will take a look into it and update you. Can we change the label to enhancement as this test seems to be working fine and we need to ensure it takes lesser time to execute?

**Comment by tarekziade** [comment]
Looks like @artem-shelkovnikov is looking into this in https://github.com/elastic/connectors-python/pull/322

**Comment by tarekziade** [comment]
fixed by https://github.com/elastic/connectors-python/pull/322
