### ISSUE TITLE
BadRequestError: failed to parse field [indexed_document_volume] of type [integer]

### ISSUE THREAD

**Issue by prashant-elastic** [elastic/connectors-python#735]
## Bug Description
BadRequestError: 400, 'mapper_parsing_exception' failed to parse field [indexed_document_volume] of type [integer]

### To Reproduce
1. Create an index in elasticsearch
2. Do the necessary changes in config.yml file
3. Exexcute make run command to execute the connector
4. Move over to the configurations tab in kibana UI and make sharepoint connector related configurations
5. Observe sync in progress and wait for it to be completed

## Expected behavior
All sharepoint documents should be successfully indexed in Elasticsearch

## Actual behavior
BadRequestError: 400, 'mapper_parsing_exception' failed to parse field [indexed_document_volume] of type [integer]

## Screenshots
![mapper_parsing](https://user-images.githubusercontent.com/103035276/230049993-c6f13b68-9934-41e5-9531-c423c0dde48a.JPG)

## Environment

- OS: Ubuntu OS v.22.04

## Additional context
[FMWK][12:16:55][INFO] Fetcher <create: 49099 |update: 0 |delete: 0>
Exception in callback ConcurrentTasks._callback(result_callback=None)(<Task finishe...tatus': 400})>)
handle: <Handle ConcurrentTasks._callback(result_callback=None)(<Task finishe...tatus': 400})>)>
Traceback (most recent call last):
  File "/home/ubuntu/es-connectors/connectors/sync_job_runner.py", line 131, in execute
    await self._sync_done(sync_status=sync_status, sync_error=fetch_error)
  File "/home/ubuntu/es-connectors/connectors/sync_job_runner.py", line 170, in _sync_done
    await self.sync_job.done(ingestion_stats=ingestion_stats)
  File "/home/ubuntu/es-connectors/connectors/byoc.py", line 237, in done
    await self._terminate(
  File "/home/ubuntu/es-connectors/connectors/byoc.py", line 275, in _terminate
    await self.index.update(doc_id=[self.id](http://self.id/), doc=doc)
  File "/home/ubuntu/es-connectors/connectors/es/index.py", line 72, in update
    await self.client.update(
  File "/home/ubuntu/es-connectors/lib/python3.10/site-packages/elasticsearch/_async/client/__init__.py", line 4513, in update
    return await self.perform_request(  # type: ignore[return-value]
  File "/home/ubuntu/es-connectors/lib/python3.10/site-packages/elasticsearch/_async/client/_base.py", line 321, in perform_request
    raise HTTP_EXCEPTIONS.get(meta.status, ApiError)(
elasticsearch.BadRequestError: BadRequestError(400, 'mapper_parsing_exception', "failed to parse field [indexed_document_volume] of type [integer] in document with id 'XmfoS4cBVSm7nRdw6PPq'. Preview of field's value: '13167265024'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/ubuntu/es-connectors/connectors/utils.py", line 318, in _callback
    raise task.exception()
  File "/home/ubuntu/es-connectors/connectors/sync_job_runner.py", line 135, in execute
    await self._sync_done(sync_status=JobStatus.ERROR, sync_error=e)
  File "/home/ubuntu/es-connectors/connectors/sync_job_runner.py", line 164, in _sync_done
    await self.sync_job.fail(sync_error, ingestion_stats=ingestion_stats)
  File "/home/ubuntu/es-connectors/connectors/byoc.py", line 242, in fail
    await self._terminate(
  File "/home/ubuntu/es-connectors/connectors/byoc.py", line 275, in _terminate
    await self.index.update(doc_id=[self.id](http://self.id/), doc=doc)
  File "/home/ubuntu/es-connectors/connectors/es/index.py", line 72, in update
    await self.client.update(
  File "/home/ubuntu/es-connectors/lib/python3.10/site-packages/elasticsearch/_async/client/__init__.py", line 4513, in update
    return await self.perform_request(  # type: ignore[return-value]
  File "/home/ubuntu/es-connectors/lib/python3.10/site-packages/elasticsearch/_async/client/_base.py", line 321, in perform_request
    raise HTTP_EXCEPTIONS.get(meta.status, ApiError)(
elasticsearch.BadRequestError: BadRequestError(400, 'mapper_parsing_exception', "failed to parse field [indexed_document_volume] of type [integer] in document with id 'XmfoS4cBVSm7nRdw6PPq'. Preview of field's value: '13167265024'")

**Comment by artem-shelkovnikov** [comment]
cc @wangch079

**Comment by wangch079** [comment]
Hi @prashant-elastic , may I know which version/branch you are running?

**Comment by parth-elastic** [comment]
We checked on `main` branch with elastic `v8.7.0` on cloud

**Comment by parth-elastic** [comment]
Also please note that, The issue is occurring when we are working with the larger data [~10 GB & ~49000 objects].
For small and medium data it is working fine.

**Comment by wangch079** [comment]
>Also please note that, The issue is occurring when we are working with the larger data [~10 GB & ~49000 objects].

Can I get a copy of the data set?

**Comment by akanshi-elastic** [comment]
> > Also please note that, The issue is occurring when we are working with the larger data [~10 GB & ~49000 objects].
> 
> Can I get a copy of the data set?

shared you on slack 1:1

**Comment by khusbu-crest** [comment]
@wangch079 Is there any update on this issue? 
We are kind of blocked to check the performance of the connectors because of this issue. While Indexing large data sets (~14k), this issue appears and the script execution gets interrupted hence we are unable to complete the performance testing.

**Comment by artem-shelkovnikov** [comment]
I think we're overflowing the integer field for `indexed_document_volume` and need a bigger data type to be able to store the bytes. Additionally we can switch to storing KB instead of B.

**Comment by wangch079** [comment]
As @artem-shelkovnikov pointed out, we use `integer` for `indexed_document_volume`, which only supports maximum `2^31-1`. `indexed_document_volume` stores the number of `bytes`, so the maximum is only around 2 GB+. We can change it to `unsigned_long`, which supports a maximum `2^64-1`, which is around 18 Exa Bytes (1000 PB).

cc. @danajuratoni This will make any connector trying to sync any source with more than 2 GB of data fail in Ruby (since 8.6) and Python (since 8.7.1). do you think we should document it?

8.7.1 is not released yet, but I don't think this can be considered a blocker. We could fix it in 8.8

**Comment by wangch079** [comment]
For @ppf2 reported issue, this is because the job is not seeing any update for more than 60 seconds (supposed to receive a heartbeat every 10 seconds), and is marked as `error`. But the job is actually running.

This can happen when the job reporting task got no chance to run for more than 60 seconds, which is rare. I will look into this issue separately.

**Comment by seanstory** [comment]
Based on [this slack thread](https://elastic.slack.com/archives/C01795T48LQ/p1681748531281409), I'm reverting the above 3 PRs. Changing the field type of an existing field in our schema would require a redindex operation, which Enterprise Search doesn't currently execute on startup. This mapping change would make any existing deployment fail to be able to upgrade to 8.8.

Instead, in a separate set of PRs, Chenhui and I will change these fields from representing `byte` counts to representing `MB` counts. This raises our limit from ~2GB to ~2PB, which seems much less likely to constrain us.

**Comment by wangch079** [comment]
Regarding this issue: https://github.com/elastic/connectors-python/issues/735#issuecomment-1510993433, I tested locally but I can't reproduce it. I guess somehow the sync was stuck somewhere for more than 60 seconds, causing the job marked as idle.
